package Enums;

public enum MessageType
{
		Login,
		homeRequestNum,
		supervisorHomeRequestNum,
		IThomeRequestNum,
		ShowReqUser,
		ShowReqIT,
		SearchReqSupervisor,
		ShowEmployeeList,
		submitRequireMoreInfo,
		SearchReqUser,
		SearchReqIT,
		AddRequest,
		addTimeEstimated,
		showRequestDetailsUser,
		superviserRequestShow,
		approveEvaluationReport,
		viewTime,
		suspendRequest,
		closeRequest,
		showRequestDetailsIT, 
		superviserExtensionRequest,
		SupervisorUpdateRequest,
		changeExecuter,
		getListOfIT,
		ITEvaluationReport1, ITjobInReq, ITgetReqStage, AddExtensionRequest,
		ITSubmitEvaluationReport, ITgetLocation, ITshowEvaluationReport,
		ITFailurReport,
		showRequestDetailsSuperviser,
		SupervisorTimeRequest, SupervisorListIt,superviserExtensionRequestAnswer,
		MhomeRequestNum,
		submitEvaluationReport,
		renewRequest,
		MangerShowMessages,
		MangerUpdateMessages,
		showRequestDetailsITManager,
		MangerRequestShow, SearchReqManager, ITsubmitRequireMoreInfo,
		addTimeEstimatedPerformance, ITchangeCompleted, 
		ITTestApproval, denyEvaluationReport, ITShowEmployeeList, ITSaveTester, SwitchPositions
}
