package Enums;

public enum MessageTypeS 
{
	Login,
	LoginFail,
	homeRequestNum,
	supervisorHomeRequestNum,
	IThomeRequestNum,
	ShowReqUser,
	ShowReqIT,
	ShowEmployeeList,
	SearchReqSupervisor,
	SearchReqUser,
	SearchReqIT,
	AddRequest,
	addTimeEstimated,
	showRequestDetailsUser,
	submitRequireMoreInfo,
	superviserRequestShow,
	suspendRequest,
	closeRequest,
	approveEvaluationReport,
	showRequestDetailsIT,
	superviserExtensionRequest,
	SupervisorUpdateRequest,
	changeExecuter,
	submitEvaluationReport,
	getListOfIT,
	ITjobInReq, ITgetReqStage, AddExtensionRequest, ITSubmitEvaluationReport, 
	ITgetLocation, ITshowEvaluationReport,
	ITFailurReport,
	showRequestDetailsSuperviser,
	SupervisorTimeRequest,
	SupervisorListIt,superviserExtensionRequestAnswer,
	MhomeRequestNum,
	MangerRequestShow,SearchReqManager,renewRequest
}
