package Enums;

public enum MessageTypeS 
{
	Login,LoginFailConnected,
	LoginFail,
	homeRequestNum,
	supervisorHomeRequestNum,
	IThomeRequestNum,
	ShowReqUser,
	ShowReqIT,
	ShowEmployeeList,
	SearchReqSupervisor,
	SearchReqUser,
	SearchReqIT,
	AddRequest,
	addTimeEstimated,
	showRequestDetailsUser,
	submitRequireMoreInfo,
	superviserRequestShow,
	viewTime,
	suspendRequest,
	closeRequest,
	approveEvaluationReport,
	showRequestDetailsIT,
	superviserExtensionRequest,
	SupervisorUpdateRequest,
	changeExecuter,
	submitEvaluationReport,
	getListOfIT,
	ITjobInReq, ITgetReqStage, AddExtensionRequest, ITSubmitEvaluationReport, 
	ITgetLocation, ITshowEvaluationReport,
	ITFailurReport,
	showRequestDetailsSuperviser,
	SupervisorTimeRequest,
	SupervisorListIt,superviserExtensionRequestAnswer,
	MhomeRequestNum,
	MangerRequestShow,SearchReqManager,renewRequest,MangerShowMessages,MangerUpdateMessages,
	ITsubmitRequireMoreInfo, addTimeEstimatedPerformance, showRequestDetailsITManager,
	ITShowEmployeeList, ITSaveTester,SwitchPositions,
	SuperviserShowMessages,SuperviserUpdateMessages, ITaddTimeEstimated, SupervisorApproveEvluationTime, approveTime, 

}
