package Enums;
/** Type of the respond of Server */
public enum MessageTypeS 
{
	Login,LoginFailConnected,
	LoginFail,
	homeRequestNum,
	supervisorHomeRequestNum,
	IThomeRequestNum,
	ShowReqUser,
	ShowReqIT,
	ShowEmployeeList,
	SearchReqSupervisor,
	SearchReqUser,
	SearchReqIT,
	AddRequest,
	addTimeEstimated,
	showRequestDetailsUser,
	submitRequireMoreInfo,
	superviserRequestShow,
	viewTime,
	suspendRequest,
	closeRequest,
	approveEvaluationReport,
	showRequestDetailsIT,
	superviserExtensionRequest,
	SupervisorUpdateRequest,
	changeExecuter,
	submitEvaluationReport,
	getListOfIT,
	ITjobInReq, ITgetReqStage, AddExtensionRequest, ITSubmitEvaluationReport, 
	ITgetLocation, ITshowEvaluationReport,
	ITFailurReport,
	showRequestDetailsSuperviser,
	SupervisorTimeRequest,
	SupervisorListIt,superviserExtensionRequestAnswer,
	MhomeRequestNum,
	MangerRequestShow,SearchReqManager,renewRequest,MangerShowMessages,MangerUpdateMessages,
	ITsubmitRequireMoreInfo, addTimeEstimatedPerformance, showRequestDetailsITManager,
	ITShowEmployeeList, ITSaveTester,SwitchPositions,
	SuperviserShowMessages,SuperviserUpdateMessages, ITaddTimeEstimated, SupervisorApproveEvluationTime, 
	approveTime, SupervisorDenyEvluationTime, SupervisorApproveExecutionTime, makeActiveSuClo, 
	makePerformenct, makeDelays, ITshowReqAgain, 
	ITrequestDaysLeft,showattachfile, superviserAttachFile, superviserAttachFileM, superviserAttachFileIT, viewrecentreport, SupervisorUpdateRequest1

}
